#!/bin/bash

input_data=""
while IFS= read -r line; do
    if [ "$line" = "EOF" ]; then
        break
    fi
    input_data+="$line\n"
    #echo $line | python3 tool.py | sed -e '$s/├/└/' -e '1s/├/┌/' | sed -e 's/^/      /'
done
#echo $input_data
#s=$(echo $input_data | tr -d '\n' )
#echo $s
echo "$input_data" | python3 tool.py | sed -e '$s/├/└/' -e '3s/├/┌/' | sed -e 's/^/                   /' | sed -e '1,2d'
